/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barraThread;

/**
 *
 * @author kevindominguez
 */
public class BarraThread extends javax.swing.JFrame {

    /**
     * Creates new form BarraThread
     */
    public BarraThread() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHiloUno = new javax.swing.JLabel();
        lblHiloDos = new javax.swing.JLabel();
        pgbHiloUno = new javax.swing.JProgressBar();
        pgbHiloDos = new javax.swing.JProgressBar();
        lblHiloTres = new javax.swing.JLabel();
        pgbHiloTres = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        lblPrimero = new javax.swing.JLabel();
        lblTercero = new javax.swing.JLabel();
        lblSegundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHiloUno.setText("Hilo 1");

        lblHiloDos.setText("Hilo 2");

        lblHiloTres.setText("Hilo 3");

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblPrimero.setText("Ganador: ");

        lblTercero.setText("Tercero");

        lblSegundo1.setText("Segundo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHiloTres)
                    .addComponent(lblHiloDos)
                    .addComponent(lblHiloUno)
                    .addComponent(pgbHiloUno, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(pgbHiloDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgbHiloTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTercero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblSegundo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHiloUno)
                .addGap(18, 18, 18)
                .addComponent(pgbHiloUno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblHiloDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgbHiloDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblHiloTres)
                .addGap(18, 18, 18)
                .addComponent(pgbHiloTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(lblPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(370, Short.MAX_VALUE)
                    .addComponent(lblSegundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        final int max = 100;
        pgbHiloUno.setMaximum(max);
        pgbHiloDos.setMaximum(max);
        pgbHiloTres.setMaximum(max);
        new Thread() {

            int num;
            int carga;

            @Override
            public void run() {
                while (pgbHiloUno.getValue() < max) {
                    try {
                        num = (int) (Math.random() * 10);
                        carga += num;
                        pgbHiloUno.setValue(carga);
                        pgbHiloUno.repaint();
                        Thread.currentThread().sleep(1000);
                        System.out.println(num);
                        if (carga >= 100) {
                            lblPrimero.setText("Hilo Uno");
                            System.out.println("Hilo uno");
                        }
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }.start();

        new Thread() {
            int num;
            int carga;

            @Override
            public void run() {
                while (pgbHiloDos.getValue() < max) {
                    try {
                        num = (int) (Math.random() * 10);
                        carga += num;
                        pgbHiloDos.setValue(carga);
                        pgbHiloDos.repaint();
                        Thread.currentThread().sleep(1000);
                        if (carga >= 100) {
                            lblPrimero.setText("Hilo Dos");
                            System.out.println("Hilo Dos");
                        }
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }.start();

        new Thread() {
            int num;
            int carga;

            @Override
            public void run() {
                while (pgbHiloTres.getValue() < max) {
                    try {
                        num = (int) (Math.random() * 10);
                        carga += num;
                        pgbHiloTres.setValue(carga);
                        pgbHiloTres.repaint();
                        Thread.currentThread().sleep(1000);
                        if (carga >= 100) {
                            lblPrimero.setText("Hilo Tres");
                            System.out.println("Hilo Tres");
                        }
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }.start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarraThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarraThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarraThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblHiloDos;
    private javax.swing.JLabel lblHiloTres;
    private javax.swing.JLabel lblHiloUno;
    private javax.swing.JLabel lblPrimero;
    private javax.swing.JLabel lblSegundo1;
    private javax.swing.JLabel lblTercero;
    private javax.swing.JProgressBar pgbHiloDos;
    private javax.swing.JProgressBar pgbHiloTres;
    private javax.swing.JProgressBar pgbHiloUno;
    // End of variables declaration//GEN-END:variables
}
